server:  
#配置端口
  port: 8080  
  session-timeout: 30  
  tomcat.max-threads: 0  
  tomcat.uri-encoding: UTF-8  
  
spring: 
#数据库配置 
  datasource:  
    url: jdbc:mysql://localhost:3306/wcgfirst  
    username : root  
    password : root  
    driverClassName : com.mysql.jdbc.Driver  